# Generated by Django 2.1.3 on 2020-03-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0014_auto_20200209_1244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
