# Generated by Django 2.1.3 on 2020-03-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0015_delete_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='year',
            new_name='college',
        ),
    ]
